// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: api/event.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Event 统一事件结构（protobuf 版本）
type Event struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Id        string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type      string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Topic     string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TraceId   string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	Source    string                 `protobuf:"bytes,6,opt,name=source,proto3" json:"source,omitempty"`
	Version   string                 `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_Pod
	//	*Event_Task
	//	*Event_Policy
	//	*Event_Component
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_event_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_event_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Event) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Event) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *Event) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Event) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetPod() *PodEventPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_Pod); ok {
			return x.Pod
		}
	}
	return nil
}

func (x *Event) GetTask() *TaskEventPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_Task); ok {
			return x.Task
		}
	}
	return nil
}

func (x *Event) GetPolicy() *PolicyEventPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_Policy); ok {
			return x.Policy
		}
	}
	return nil
}

func (x *Event) GetComponent() *ComponentEventPayload {
	if x != nil {
		if x, ok := x.Payload.(*Event_Component); ok {
			return x.Component
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_Pod struct {
	Pod *PodEventPayload `protobuf:"bytes,10,opt,name=pod,proto3,oneof"`
}

type Event_Task struct {
	Task *TaskEventPayload `protobuf:"bytes,11,opt,name=task,proto3,oneof"`
}

type Event_Policy struct {
	Policy *PolicyEventPayload `protobuf:"bytes,12,opt,name=policy,proto3,oneof"`
}

type Event_Component struct {
	Component *ComponentEventPayload `protobuf:"bytes,13,opt,name=component,proto3,oneof"`
}

func (*Event_Pod) isEvent_Payload() {}

func (*Event_Task) isEvent_Payload() {}

func (*Event_Policy) isEvent_Payload() {}

func (*Event_Component) isEvent_Payload() {}

// PodEventPayload Pod 相关事件负载
type PodEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PodName       string                 `protobuf:"bytes,1,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodNamespace  string                 `protobuf:"bytes,2,opt,name=pod_namespace,json=podNamespace,proto3" json:"pod_namespace,omitempty"`
	PodUid        string                 `protobuf:"bytes,3,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	PodId         string                 `protobuf:"bytes,4,opt,name=pod_id,json=podId,proto3" json:"pod_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Extensions    map[string]string      `protobuf:"bytes,7,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 不可预知的扩展字段（string-only fallback）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PodEventPayload) Reset() {
	*x = PodEventPayload{}
	mi := &file_api_event_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PodEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PodEventPayload) ProtoMessage() {}

func (x *PodEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PodEventPayload.ProtoReflect.Descriptor instead.
func (*PodEventPayload) Descriptor() ([]byte, []int) {
	return file_api_event_proto_rawDescGZIP(), []int{1}
}

func (x *PodEventPayload) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *PodEventPayload) GetPodNamespace() string {
	if x != nil {
		return x.PodNamespace
	}
	return ""
}

func (x *PodEventPayload) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *PodEventPayload) GetPodId() string {
	if x != nil {
		return x.PodId
	}
	return ""
}

func (x *PodEventPayload) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *PodEventPayload) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *PodEventPayload) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// TaskEventPayload 任务状态事件负载
type TaskEventPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 核心字段（强类型）
	TaskId           string `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	OldState         string `protobuf:"bytes,2,opt,name=old_state,json=oldState,proto3" json:"old_state,omitempty"`
	NewState         string `protobuf:"bytes,3,opt,name=new_state,json=newState,proto3" json:"new_state,omitempty"`
	CurrentState     string `protobuf:"bytes,4,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	TargetState      string `protobuf:"bytes,5,opt,name=target_state,json=targetState,proto3" json:"target_state,omitempty"`
	Action           string `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	Timestamp        int64  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	PolicyId         string `protobuf:"bytes,8,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	TriggerEventType string `protobuf:"bytes,9,opt,name=trigger_event_type,json=triggerEventType,proto3" json:"trigger_event_type,omitempty"`
	TriggerEventId   string `protobuf:"bytes,10,opt,name=trigger_event_id,json=triggerEventId,proto3" json:"trigger_event_id,omitempty"`
	// 扩展字段（弱类型，承载 t.Metadata 中的动态 key）
	// 常用 key 预定义为强类型字段，其余走 map<string, string> fallback
	Extensions    map[string]string `protobuf:"bytes,11,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskEventPayload) Reset() {
	*x = TaskEventPayload{}
	mi := &file_api_event_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskEventPayload) ProtoMessage() {}

func (x *TaskEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskEventPayload.ProtoReflect.Descriptor instead.
func (*TaskEventPayload) Descriptor() ([]byte, []int) {
	return file_api_event_proto_rawDescGZIP(), []int{2}
}

func (x *TaskEventPayload) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskEventPayload) GetOldState() string {
	if x != nil {
		return x.OldState
	}
	return ""
}

func (x *TaskEventPayload) GetNewState() string {
	if x != nil {
		return x.NewState
	}
	return ""
}

func (x *TaskEventPayload) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *TaskEventPayload) GetTargetState() string {
	if x != nil {
		return x.TargetState
	}
	return ""
}

func (x *TaskEventPayload) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TaskEventPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TaskEventPayload) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *TaskEventPayload) GetTriggerEventType() string {
	if x != nil {
		return x.TriggerEventType
	}
	return ""
}

func (x *TaskEventPayload) GetTriggerEventId() string {
	if x != nil {
		return x.TriggerEventId
	}
	return ""
}

func (x *TaskEventPayload) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// PolicyEventPayload 策略匹配事件负载
type PolicyEventPayload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 核心字段（强类型）
	PolicyId           string `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	TriggerEventType   string `protobuf:"bytes,2,opt,name=trigger_event_type,json=triggerEventType,proto3" json:"trigger_event_type,omitempty"`
	TriggerEventSource string `protobuf:"bytes,3,opt,name=trigger_event_source,json=triggerEventSource,proto3" json:"trigger_event_source,omitempty"`
	TriggerEventId     string `protobuf:"bytes,4,opt,name=trigger_event_id,json=triggerEventId,proto3" json:"trigger_event_id,omitempty"`
	Timestamp          int64  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 扩展字段（弱类型，承载 match.Expansion 中的动态 key）
	// 常用 key 预定义为强类型字段，其余走 map<string, string> fallback
	Extensions    map[string]string `protobuf:"bytes,6,rep,name=extensions,proto3" json:"extensions,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyEventPayload) Reset() {
	*x = PolicyEventPayload{}
	mi := &file_api_event_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyEventPayload) ProtoMessage() {}

func (x *PolicyEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyEventPayload.ProtoReflect.Descriptor instead.
func (*PolicyEventPayload) Descriptor() ([]byte, []int) {
	return file_api_event_proto_rawDescGZIP(), []int{3}
}

func (x *PolicyEventPayload) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyEventPayload) GetTriggerEventType() string {
	if x != nil {
		return x.TriggerEventType
	}
	return ""
}

func (x *PolicyEventPayload) GetTriggerEventSource() string {
	if x != nil {
		return x.TriggerEventSource
	}
	return ""
}

func (x *PolicyEventPayload) GetTriggerEventId() string {
	if x != nil {
		return x.TriggerEventId
	}
	return ""
}

func (x *PolicyEventPayload) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PolicyEventPayload) GetExtensions() map[string]string {
	if x != nil {
		return x.Extensions
	}
	return nil
}

// ComponentEventPayload 组件事件负载
type ComponentEventPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	CurrentState  string                 `protobuf:"bytes,2,opt,name=current_state,json=currentState,proto3" json:"current_state,omitempty"`
	TargetState   string                 `protobuf:"bytes,3,opt,name=target_state,json=targetState,proto3" json:"target_state,omitempty"`
	ComponentName string                 `protobuf:"bytes,4,opt,name=component_name,json=componentName,proto3" json:"component_name,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentEventPayload) Reset() {
	*x = ComponentEventPayload{}
	mi := &file_api_event_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentEventPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentEventPayload) ProtoMessage() {}

func (x *ComponentEventPayload) ProtoReflect() protoreflect.Message {
	mi := &file_api_event_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentEventPayload.ProtoReflect.Descriptor instead.
func (*ComponentEventPayload) Descriptor() ([]byte, []int) {
	return file_api_event_proto_rawDescGZIP(), []int{4}
}

func (x *ComponentEventPayload) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ComponentEventPayload) GetCurrentState() string {
	if x != nil {
		return x.CurrentState
	}
	return ""
}

func (x *ComponentEventPayload) GetTargetState() string {
	if x != nil {
		return x.TargetState
	}
	return ""
}

func (x *ComponentEventPayload) GetComponentName() string {
	if x != nil {
		return x.ComponentName
	}
	return ""
}

func (x *ComponentEventPayload) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ComponentEventPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_api_event_proto protoreflect.FileDescriptor

const file_api_event_proto_rawDesc = "" +
	"\n" +
	"\x0fapi/event.proto\x12\x05event\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa1\x03\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x16\n" +
	"\x06source\x18\x06 \x01(\tR\x06source\x12\x18\n" +
	"\aversion\x18\a \x01(\tR\aversion\x12*\n" +
	"\x03pod\x18\n" +
	" \x01(\v2\x16.event.PodEventPayloadH\x00R\x03pod\x12-\n" +
	"\x04task\x18\v \x01(\v2\x17.event.TaskEventPayloadH\x00R\x04task\x123\n" +
	"\x06policy\x18\f \x01(\v2\x19.event.PolicyEventPayloadH\x00R\x06policy\x12<\n" +
	"\tcomponent\x18\r \x01(\v2\x1c.event.ComponentEventPayloadH\x00R\tcomponentB\t\n" +
	"\apayload\"\x9d\x03\n" +
	"\x0fPodEventPayload\x12\x19\n" +
	"\bpod_name\x18\x01 \x01(\tR\apodName\x12#\n" +
	"\rpod_namespace\x18\x02 \x01(\tR\fpodNamespace\x12\x17\n" +
	"\apod_uid\x18\x03 \x01(\tR\x06podUid\x12\x15\n" +
	"\x06pod_id\x18\x04 \x01(\tR\x05podId\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12:\n" +
	"\x06labels\x18\x06 \x03(\v2\".event.PodEventPayload.LabelsEntryR\x06labels\x12F\n" +
	"\n" +
	"extensions\x18\a \x03(\v2&.event.PodEventPayload.ExtensionsEntryR\n" +
	"extensions\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe0\x03\n" +
	"\x10TaskEventPayload\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\told_state\x18\x02 \x01(\tR\boldState\x12\x1b\n" +
	"\tnew_state\x18\x03 \x01(\tR\bnewState\x12#\n" +
	"\rcurrent_state\x18\x04 \x01(\tR\fcurrentState\x12!\n" +
	"\ftarget_state\x18\x05 \x01(\tR\vtargetState\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x1b\n" +
	"\tpolicy_id\x18\b \x01(\tR\bpolicyId\x12,\n" +
	"\x12trigger_event_type\x18\t \x01(\tR\x10triggerEventType\x12(\n" +
	"\x10trigger_event_id\x18\n" +
	" \x01(\tR\x0etriggerEventId\x12G\n" +
	"\n" +
	"extensions\x18\v \x03(\v2'.event.TaskEventPayload.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xe3\x02\n" +
	"\x12PolicyEventPayload\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12,\n" +
	"\x12trigger_event_type\x18\x02 \x01(\tR\x10triggerEventType\x120\n" +
	"\x14trigger_event_source\x18\x03 \x01(\tR\x12triggerEventSource\x12(\n" +
	"\x10trigger_event_id\x18\x04 \x01(\tR\x0etriggerEventId\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12I\n" +
	"\n" +
	"extensions\x18\x06 \x03(\v2).event.PolicyEventPayload.ExtensionsEntryR\n" +
	"extensions\x1a=\n" +
	"\x0fExtensionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd3\x01\n" +
	"\x15ComponentEventPayload\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12#\n" +
	"\rcurrent_state\x18\x02 \x01(\tR\fcurrentState\x12!\n" +
	"\ftarget_state\x18\x03 \x01(\tR\vtargetState\x12%\n" +
	"\x0ecomponent_name\x18\x04 \x01(\tR\rcomponentName\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessageB%Z#github.com/sig-cloudnative/nuts/apib\x06proto3"

var (
	file_api_event_proto_rawDescOnce sync.Once
	file_api_event_proto_rawDescData []byte
)

func file_api_event_proto_rawDescGZIP() []byte {
	file_api_event_proto_rawDescOnce.Do(func() {
		file_api_event_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_event_proto_rawDesc), len(file_api_event_proto_rawDesc)))
	})
	return file_api_event_proto_rawDescData
}

var file_api_event_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_event_proto_goTypes = []any{
	(*Event)(nil),                 // 0: event.Event
	(*PodEventPayload)(nil),       // 1: event.PodEventPayload
	(*TaskEventPayload)(nil),      // 2: event.TaskEventPayload
	(*PolicyEventPayload)(nil),    // 3: event.PolicyEventPayload
	(*ComponentEventPayload)(nil), // 4: event.ComponentEventPayload
	nil,                           // 5: event.PodEventPayload.LabelsEntry
	nil,                           // 6: event.PodEventPayload.ExtensionsEntry
	nil,                           // 7: event.TaskEventPayload.ExtensionsEntry
	nil,                           // 8: event.PolicyEventPayload.ExtensionsEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_api_event_proto_depIdxs = []int32{
	9, // 0: event.Event.timestamp:type_name -> google.protobuf.Timestamp
	1, // 1: event.Event.pod:type_name -> event.PodEventPayload
	2, // 2: event.Event.task:type_name -> event.TaskEventPayload
	3, // 3: event.Event.policy:type_name -> event.PolicyEventPayload
	4, // 4: event.Event.component:type_name -> event.ComponentEventPayload
	5, // 5: event.PodEventPayload.labels:type_name -> event.PodEventPayload.LabelsEntry
	6, // 6: event.PodEventPayload.extensions:type_name -> event.PodEventPayload.ExtensionsEntry
	7, // 7: event.TaskEventPayload.extensions:type_name -> event.TaskEventPayload.ExtensionsEntry
	8, // 8: event.PolicyEventPayload.extensions:type_name -> event.PolicyEventPayload.ExtensionsEntry
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_api_event_proto_init() }
func file_api_event_proto_init() {
	if File_api_event_proto != nil {
		return
	}
	file_api_event_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_Pod)(nil),
		(*Event_Task)(nil),
		(*Event_Policy)(nil),
		(*Event_Component)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_event_proto_rawDesc), len(file_api_event_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_event_proto_goTypes,
		DependencyIndexes: file_api_event_proto_depIdxs,
		MessageInfos:      file_api_event_proto_msgTypes,
	}.Build()
	File_api_event_proto = out.File
	file_api_event_proto_goTypes = nil
	file_api_event_proto_depIdxs = nil
}
